Repository jakartaee/rest, pull requests merged in 2018-10, with the labels that each got.

#662 Add uses clauses to module-info.java
  jaxrs-api/src/main/java/module-info.java
Labels: bug

#671 JAX-RS 2.1.2 (Bug fixes ontop JAX-RS 2.1.1)
  .travis.yml
  examples/pom.xml
  jaxrs-api/.gitignore
  jaxrs-api/pom.xml
  jaxrs-api/src/main/java/module-info.java
Labels: bug, project

#678 2.1.2 Rollup
  examples/pom.xml
  jaxrs-api/pom.xml
Labels: project

#676 Added gitignore entries for Eclipse, NetBeans and VS Code
  .gitignore
Labels: project

#682 Travis CI does not support oraclejdk10 anymore
  .travis.yml
Labels: project
