Repository jakartaee/rest, pull requests merged in 2018-08, with the labels that each got.

#645 Fixed Javadoc typo: Missing closing parenthesis
  jaxrs-api/src/main/java/javax/ws/rs/client/ClientResponseFilter.java
Labels: bug, javadoc

#635 Run Travis build against more JDK versions
  .travis.yml
Labels: project

#647 Run Travis build against more JDK versions (in 2.1.1 / EE4J_8)
  .travis.yml
Labels: project

#641 public UriBuilder.newInstance()
  jaxrs-api/src/main/java/javax/ws/rs/core/UriBuilder.java
Labels: api

#642 ClientFilter need @Provider only for discovery
  jaxrs-api/src/main/java/javax/ws/rs/client/ClientRequestFilter.java
  jaxrs-api/src/main/java/javax/ws/rs/client/ClientResponseFilter.java
Labels: api, bug, clarification, javadoc

#650 Automatically trigger nightly builds
  Jenkinsfile
Labels: project

#652 Release Process: GPG Signing & OSSRH Nexus Staging
  jaxrs-api/pom.xml
Labels: project

#619 Java SE Bootstrapping API
  examples/pom.xml
  examples/src/main/java/jaxrs/examples/bootstrap/BasicJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/ClientAuthenticationJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/ExplicitJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/ExternalConfigJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/HelloWorld.java
  examples/src/main/java/jaxrs/examples/bootstrap/HttpsJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/NativeJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/PropertyProviderJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/TlsJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/package-info.java
  jaxrs-api/src/main/java/javax/ws/rs/JAXRS.java
  jaxrs-api/src/main/java/javax/ws/rs/ext/RuntimeDelegate.java
  jaxrs-api/src/test/java/javax/ws/rs/JAXRSTest.java
  jaxrs-api/src/test/java/javax/ws/rs/core/RuntimeDelegateStub.java
Labels: api

#654 POM additions requested by OSSRH
  jaxrs-api/pom.xml
Labels: project

#651 Automatically trigger nightly builds
  Jenkinsfile
Labels: project
