Repository jakartaee/rest, pull requests merged in 2018-11, with the labels that each got.

#687 Removed Automatic-Module-Name from manifest
  jaxrs-api/pom.xml
Labels: project

#686 Fixed spec-version properties and Travis config for 2.1 releases
  .travis.yml
  jaxrs-api/pom.xml
Labels: project

#701 Removed Travis JDK 11 support in EE4J_8 branch
  .travis.yml
Labels: project

#692 Dependencies migrated from javax to jakarta
  jaxrs-api/pom.xml
Labels: GlassFish 5.1, project

#689 Replaced spec-version-maven-plugin with explicit configuration
  jaxrs-api/pom.xml
Labels: project

#703 Version 2.1.3
  examples/pom.xml
  jaxrs-api/pom.xml
Labels: project

#696 MediaType improvements
  jaxrs-api/src/main/java/javax/ws/rs/core/MediaType.java
Labels: enhancement, performance

#704 Excluding JRE's implied JAXB implementation with JDK11+
  jaxrs-api/pom.xml
Labels: project

#705 2.1.3 Rollup
  jaxrs-api/pom.xml
Labels: project
