Repository jakartaee/rest, pull requests merged in 2018-05, with the labels that each got.

#621 Clarify which components are returned from Configuration#getClasses()
  jaxrs-api/src/main/java/javax/ws/rs/core/Configuration.java
Labels: javadoc

#622 Minor improvements to pom.xml
  jaxrs-api/.gitignore
  jaxrs-api/pom.xml
Labels: project

#630 Fixed: Building on JDK9 using maven-surefire-plugin:2.21.0
  jaxrs-api/pom.xml
Labels: bug, project

#628 Static packaging type 'bundle' instead of property
  jaxrs-api/pom.xml
Labels: enhancement, project
