Repository jakartaee/rest, pull requests merged in 2019-03, with the labels that each got.

#744 Clarify in which situations MBW/MBR pipelines are executed (#711)
  jaxrs-api/src/main/java/javax/ws/rs/ext/MessageBodyReader.java
  jaxrs-api/src/main/java/javax/ws/rs/ext/MessageBodyWriter.java
Labels: clarification, javadoc

#735 Fix for #734 (Javadoc fails on JDK 11 and later)
  jaxrs-api/pom.xml
Labels: project

#748 Update Request.evaluatePreconditions() to match RFC 7232
  jaxrs-api/src/main/java/javax/ws/rs/core/Request.java
Labels: enhancement, tck

#685 CI on JDK12
  .travis.yml
Labels: project
