Repository jakartaee/rest, pull requests merged in 2019-12, with the labels that each got.

#813 [#804] Spec: Use “https://” instead of “http://” for any external link
  jaxrs-spec/assembly.xml
  jaxrs-spec/pom.xml
  jaxrs-spec/src/main/asciidoc/chapters/appendix/_bibliography.adoc
Labels: spec

#814 [#804] Spec: Fix text for Filters and Interceptors: Introduction and Filter
  jaxrs-spec/src/main/asciidoc/chapters/filters_and_interceptors/_filters.adoc
  jaxrs-spec/src/main/asciidoc/chapters/filters_and_interceptors/_introduction_filters.adoc
Labels: spec

#818 [#804] Modifying references to the JCP with corresponding Eclipse processes (excluding Activation and JAX-WS)
  jaxrs-spec/src/main/asciidoc/chapters/appendix/_bibliography.adoc
Labels: spec

#820 Migration of Jenkins files (Fixed Nightly Build)
  Jenkinsfile
Labels: project

#823 Renamed 2.2-SNAPSHOT -> 3.1-SNAPSHOT
  examples/pom.xml
  jaxrs-api/pom.xml
  jaxrs-spec/pom.xml
Labels: project

#810 [#554] Fix javadoc for Response.created()
  jaxrs-api/src/main/java/jakarta/ws/rs/core/Response.java
Labels: bug, spec

#830 [#816] Update the license names in pom.xml to use proper SPDX identifier
  jaxrs-api/pom.xml
Labels: project
