Repository jakartaee/rest, pull requests merged in 2020-01, with the labels that each got.

#829 [Spec] Fixed: Link to current spec
  _config.yml
Labels: project

#821 Migrated to https://jakarta.oss.sonatype.org
  jaxrs-api/pom.xml
Labels: project

#827 Corrected `@since 2.2` to `@since 3.1` for API changes
  examples/src/main/java/jaxrs/examples/bootstrap/BasicJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/ClientAuthenticationJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/ExplicitJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/ExternalConfigJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/HelloWorld.java
  examples/src/main/java/jaxrs/examples/bootstrap/HttpsJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/NativeJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/PropertyProviderJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/TlsJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/package-info.java
  jaxrs-api/src/main/java/jakarta/ws/rs/SeBootstrap.java
  jaxrs-api/src/main/java/jakarta/ws/rs/core/UriBuilder.java
  jaxrs-api/src/test/java/jakarta/ws/rs/SeBootstrapTest.java
Labels: javadoc

#833 [#606] Clarify when to call onError vs onComplete
  jaxrs-api/src/main/java/jakarta/ws/rs/sse/SseEventSource.java
Labels: clarification, javadoc
