Repository jakartaee/rest, pull requests merged in 2021-07, with the labels that each got.

#980 Preparing examples v3.1
  examples/pom.xml
Labels: project

#981 Travis openjdk17
  .travis.yml
Labels: project

#983 Version Bump: Checkstyle 8.43
  etc/config/checkstyle.xml
  examples/pom.xml
  jaxrs-api/pom.xml
Labels: project

#984 Fixed Javadoc Warnings
  jaxrs-api/src/main/java/jakarta/ws/rs/core/EntityPart.java
Labels: javadoc

#996 Set JDK version to 11 on Jenkins
  Jenkinsfile
Labels: build

#994 Initial setup for GitHub Actions
  .github/workflows/maven-package.yml
Labels: build

#1000 Version Bump: Maven Checkstyle Plugin 3.1.2 + Checkstyle 8.44
  etc/config/checkstyle.xml
  examples/pom.xml
  jaxrs-api/pom.xml
Labels: project

#982 Preparing API POM for v3.1
  jaxrs-api/pom.xml
Labels: project

#991 Cleanup of pom names and relative paths to avoid warnings
  examples/pom.xml
  jaxrs-api/pom.xml
  jaxrs-api/src/main/java/jakarta/ws/rs/core/EntityPart.java
  jaxrs-spec/pom.xml
  jaxrs-tck/pom.xml
  jersey-tck/pom.xml
  pom.xml
Labels: enhancement

#997 Removing inactive committers
  jaxrs-spec/src/main/asciidoc/chapters/introduction/_project_team.adoc
Labels: spec
