Repository jakartaee/rest, pull requests merged in 2021-09, with the labels that each got.

#1005 [1004] Wrap service loader calls in privileged actions if the securit…
  jaxrs-api/src/main/java/jakarta/ws/rs/client/ClientBuilder.java
  jaxrs-api/src/main/java/jakarta/ws/rs/client/FactoryFinder.java
  jaxrs-api/src/main/java/jakarta/ws/rs/ext/FactoryFinder.java
  jaxrs-api/src/main/java/jakarta/ws/rs/sse/FactoryFinder.java
Labels: security

#1010 Provides boilerplate simplification for SeBootstrap API
  examples/src/main/java/jaxrs/examples/bootstrap/BasicJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/ClientAuthenticationJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/ExplicitJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/ExternalConfigJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/HttpsJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/NativeJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/PropertyProviderJavaSeBootstrapExample.java
  examples/src/main/java/jaxrs/examples/bootstrap/TlsJavaSeBootstrapExample.java
  jaxrs-api/src/main/java/jakarta/ws/rs/SeBootstrap.java
  jaxrs-api/src/main/java/jakarta/ws/rs/ext/RuntimeDelegate.java
  jaxrs-api/src/test/java/jakarta/ws/rs/SeBootstrapTest.java
Labels: enhancement, api

#1017 Use GenericEntity for List<EntityPart> entity in EntityPart javadoc.
  jaxrs-api/src/main/java/jakarta/ws/rs/core/EntityPart.java
Labels: javadoc
